Assignment1/Assignment1_MFerrari.py
Assignment1/Assignment1_guide.py

I'm adding the first assignment

Assignment 1

---

Assignment1/Assignment1_ManuelRossi.py

Adding assignment 1

---

Assignment1/Assignment1_GiuliaSora.py

adding assignment

---

Assignment1/Assignment1_HCordoba.py

I am addint the assignment #1 of Example B

I am adding the assignment 1

---

Assignment1/Assignment1_ABlanco.py

I am sending the assignment 1.
Ana Blanco Hernández

 adding the assignment

---

Assignment2/Assignment2_MFerrari.py

I'm adding the second assignment

Adding assignment 2

---

Assignment2/Assignment_2_DSchiavo.py

 adding the assignment_2

---

Assignment2/Assignment2_ARomanelli.py
Assignment2/Assignment2_Guidelines.py

adding assignment2

---

Assignment2/Assignment2_HCordoba.py

 I am adding the assignment #2

---

Assignment2/Assignment_2_FRossetti.py

I don't know if I properly upload the Assignement 2.

Adding Assignement2

---

Assignment2/Assignment2_AnaBlanco.py

 adding the assignment 2

---

Assignment2/Assignment2_BuketOzcan.py

assignment2

---

Assignment2/Assignment_2_mbarlay.py

Assignment_2_mbarlay.py

---

Assignment3/Assignment3_buketozcan.py

added air gap to the previous assignment and solved with "def"

assignment3

---

Assignment3/Assignment3_HCordoba.py

Adding assignment #3

---

Assignment3/Assignment3_AnaBlanco.py

The end of the assignment doesn't run. Something is wrong but I can't find the mistake. I will try to correct it.

adding my assignment

---

Assignment3/Assignment_3_DSchiavo.py

Adding the assignment

---

Assignment2/Assignment2_redo_Lorusso.py
Assignment3/Assignment3_Lorusso.py

Adding assignment 3.
Last Week i did the wrong execise so i just did the correct one.
Kind Regards,
Gianluca Lorusso

 adding assignment 3 and redo Assignment 2

---

Assignment3/Assignment3_ABlancoOK.py
Assignment4/Assignment4_AnaBlanco.py
Assignment4/wallFunctions_AnaBlanco.py

Good night! I finally found the mistake in assignment 3 and now is working. The error was that the 'for' bucle only ran once (with the first resistance of the list of resistances) because of the wrong position of the 'return' command

adding assignment 3 corrected

---

Assignment4/Assignement4_FRossetti.py
Assignment4/WallFunctions_FRossetti.py

adding Assignement

---

Assignment4/Assignment4_buketozcan.py
Assignment4/WallFunctions_buketozcan.py

Adding Assignment 4 and the wall functions

Assignment4_buketozcan

---

Assignment4/Assignment_4_mbarlay.py
Assignment4/Assignment_4_wallfunctions_mbarlay.py
Assignment5/Assignment_5_mbarlay.py

adding assignment 4, 2 folders

---

Assignment4/Assignment4_Lorusso.py
Assignment4/WallCalculation_Lorusso.py
Assignment5/Assignment5_Lorusso.py

Dear Prof,
Adding Assignment 4

adding assignment 4

---

Assignment7/Assignment6_ManuelRossi.py
Assignment7/Assignment7_ManuelRossi.py

Adding Assignments

---

Assignment7/Assignment7_GiuliaSora.py

I'm adding the assignment number 7

Adding Assignment 7

---

Assignment7/Assignment7_buketozcan.py

Assignment7_buketozcan
